name: rasa
channels:
  - nvidia/label/testing
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - brotli-python=1.0.9=py38hfa26641_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cudatoolkit=10.2.89=h713d32c_10
  - cudnn=7.6.5.32=h01f27c4_1
  - dataclasses=0.8=pyhc8e2a94_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - huggingface_hub=0.26.5=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libcblas=3.9.0=35_h0358290_openblas
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=35_h47877c9_openblas
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.5.4=hfead8bd_4
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2022.1.0=hc2b9512_224
  - nccl=2.14.3.1=h1a5f58c_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nibabel=5.2.1=pyha770c72_0
  - ninja=1.13.1=h171cf75_0
  - openssl=3.5.3=h26f9b46_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py38h06a4308_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.0.0=py38hfb59056_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.18=h955ad1f_0
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - setuptools=68.2.2=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.9.0=ha0421bc_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.4.1=py38hfb59056_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.22.0=py38ha98ab4e_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cmake==3.28.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.2
      - defusedxml==0.7.1
      - entrypoints==0.3
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.13.1
      - flake8==3.7.9
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - ftfy==6.1.3
      - future==0.18.3
      - gdown==5.0.0
      - google-auth==2.26.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.60.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.4.0
      - ipython==8.12.3
      - isoduration==20.11.0
      - isort==4.3.21
      - jinja2==3.1.3
      - joblib==1.3.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - kiwisolver==1.4.7
      - lit==17.0.6
      - littleutils==0.2.2
      - markdown==3.5.2
      - markupsafe==2.1.4
      - matplotlib==3.7.5
      - mccabe==0.6.1
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - oauthlib==3.2.2
      - ogb==1.3.6
      - opencv-python==4.9.0.80
      - outdated==0.2.2
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.2
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycodestyle==2.5.0
      - pyflakes==2.1.1
      - pyparsing==3.1.4
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tb-nightly==2.14.0a20230808
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.2.0
      - tinycss2==1.3.0
      - tokenizers==0.20.3
      - tomli==2.0.1
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.66.1
      - transformers==4.46.3
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - uri-template==1.3.0
      - urllib3==2.1.0
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.1
      - wilds==1.2.2
      - yacs==0.1.8
      - yapf==0.29.0
      - zipp==3.17.0
prefix: /home/username/anaconda3/envs/rasa